[package]
name = "strip-pandoc-template"
version = "0.1.0"
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
structopt = "0.3.22"
regex = "1.5.4"
eyre = "0.6.5"
color-eyre = "0.5.11"
itertools = "0.10"
toml = "0.5.8"